version: '3'

services:
    php:
        build:
            context: .
            dockerfile: ./.docker/php/dev.Dockerfile
        volumes:
        - ./:/var/www/html

    web:
        image: nginx:1.17
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "80:80"

    node:
        image: node:12
        user: node
        working_dir: /assets
        volumes:
            - ./:/assets
        command: npm run watch

    db:
        image: mysql:8
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata:

